### PR TITLE
Added Dark Theme

### LINKED ISSUE #91: Dark Mode for website
Implementing Dark/Light mode in Quarto is straightforward, but I'm waiting because there isn't a 'cosmo' equivalent theme for Dark mode. It would require writing some custom CSS for 'solar' theme, which is similar to 'cosmo' but have some color inconsistencies that need refining. 

@jitendravjh want to work on this - https://github.com/TuringLang/turinglang.github.io/issues/80#issuecomment-2268963967

### PR DESCRIPTION
**Pull request by jitendravjh**
Closes #91

### CODE REVIEW

**Comment by shravanngoswamii** [comment]
I think preview workflow is not working, let me fix it first!

**Comment by shravanngoswamii** [comment]
Text colors in lists is still white, is it intended to be like that?
image

**Comment by jitendravjh** [comment]
> Text colors in lists is still white, is it intended to be like that?

fixed it!

**Comment by shravanngoswamii** [comment]
I think text color in navbar will look much better if it's white!

**Comment by shravanngoswamii** [comment]
Everything looks good to me, maybe @yebai would like to see colours once —
Main Site: https://turinglang.org/pr-previews/92
Docs Site: https://turinglang.org/docs/pr-previews/509

**Review by penelopeysm — CHANGES_REQUESTED** [review]
Hi @jitendravjh, this is great work :) I like the colours a lot (despite being an always-light-mode girl)

There are some small inconsistencies in the CSS variables between the `cosmo` and `solar` themes.  You can see these here:

 - Cosmo: https://github.com/thomaspark/bootswatch/blob/v5/dist/cosmo/_variables.scss
 - Solar: https://github.com/thomaspark/bootswatch/blob/v5/dist/solar/_variables.scss

For example, `solar` sets 

```css
$breadcrumb-padding-y:              .375rem !default;
$breadcrumb-padding-x:              .75rem !default;
```

This leads to some moving around when the colour scheme is changed:

https://github.com/user-attachments/assets/7cbb2a7b-c900-415b-936c-7b8ca6a59ebb

There are a couple of ways to get around this. One is to specifically override SCSS variables like the `breadcrumb-padding` ones.

The other is to use `cosmo` as a base theme and override every single colour variable. Basically, copy all the colour variables over from the base `solar` SCSS file into `theming/theme-dark.scss` (and replace any of them that you want to tweak).

I would lean towards the latter, because using `cosmo` as a base will guarantee that we have all the non-colour CSS variables exactly the same.

**Comment by shravanngoswamii** [comment]
@jitendravjh Any updates?

**Comment by shravanngoswamii** [comment]
> The other is to use `cosmo` as a base theme and override every single colour variable. Basically, copy all the colour variables over from the base `solar` SCSS file into `theming/theme-dark.scss` (and replace any of them that you want to tweak, such as `$body-color`).

This looks much better approach to me, using this there will no to minimal chances in theme and color inconsistencies in future!

**Comment by jitendravjh** [comment]
Apologies for the delay. The requested changes have been implemented. Please review and let me know if any further adjustments are needed.
@penelopeysm @shravanngoswamii 

Main Site: https://turinglang.org/pr-previews/92
Docs Site: https://turinglang.org/docs/pr-previews/509

**Review by penelopeysm — APPROVED** [review]
Looks good!

**Review by shravanngoswamii — APPROVED** [review]

**Comment by shravanngoswamii** [comment]
Thank you, @jitendravjh!

**Pull request merged**
